# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='doctor_id',
        ),
    ]
