# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('doctor_id', models.CharField(default=None, max_length=100, null=True, unique=True)),
                ('users', models.ManyToManyField(to='users.User')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
