# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171023_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(blank=True, to='users.User'),
        ),
    ]
