# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20171023_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='doctor_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
