# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='doctor_id',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
