# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models

from django.core.management import call_command

fixture = 'specialties.json'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specialties', '0001_initial'),

    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
