# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rating_avg', models.FloatField()),
                ('rating_total', models.IntegerField(default=0)),
                ('latitude', models.CharField(max_length=100, unique=True)),
                ('longitude', models.CharField(max_length=100, unique=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='specialties.Specialty')),
                ('users', models.ManyToManyField(to='users.User')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
