# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20171023_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
