# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20171024_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
